[versions]
# Kotlin / Android
kotlin = "2.2.10"
androidGradle = "9.3.1"

# Dependency Analysis Gradle Plugin (DAGP)
# https://github.com/autonomousapps/dependency-analysis-gradle-plugin
dependencyAnalysis = "3.19.2"

# Android SDK levels
androidCompileSdk = "35"
androidMinSdk = "24"
androidTargetSdk = "35"

# Libraries used by the "app" component
kotlinxCoroutinesAndroid = "1.6.4"

[libraries]
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
library = { module = "com.example.dagp:library" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "androidGradle" }
androidKmpLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradle" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }

